document.write( '<navbar class=\"navbar navbar-expand-sm bg-dark navbar-dark fixed-top\">\n' );
document.write( '\n' );
document.write( '    <a class=\"branding-font\" href=\"/index.html\">\n' );
document.write( '        Rouxles' );
document.write( '    </a>\n' );
document.write( '\n' );
document.write( '    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsibleNavbar\">\n' );
document.write( '        <span class=\"navbar-toggler-icon\"></span>\n' );
document.write( '    </button>\n' );
document.write( '\n' );
document.write( '    <div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">\n' );
document.write( '        <ul class=\"navbar-nav\">\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"fb.html\">First Block</a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"sb.html\">Second Block</a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"cmll.html\">CMLL</a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"lse.html\">LSE</a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"reconstructions.html\">Reconstructions</a>\n' );
document.write( '            </li>\n' );
document.write( '            <li class=\"nav-item\">\n' );
document.write( '                <a class=\"nav-link\" href=\"about.html\">About</a>\n' );
document.write( '            </li>\n' );
document.write( '        </ul>\n' );
document.write( '    </div>\n' );
document.write( '\n' );
document.write( '</navbar>' );
